### ISSUE TITLE
使用中的一些问题

### ISSUE THREAD

**Issue by wzqiang1332** [Tencent/GameAISDK#29]
作为一个初学者，希望得到大佬们的指点，非常感谢。
使用windows docker的方式安装好了，在新建项目的过程中有点疑问。
scene场景是什么意思？我看教学视频里面在天天快跑中建了一个zanting的task，只是捕捉了暂停的按钮。
ai的action必须要选择scene，这两个的关系是什么？
ai的action里面的动作有down，up，swipe等操作，我现在有个人物在界面，我界面上任意地方上下左右滑动人物会同步滑动，这个动作应该怎么设置？没有固定的按钮位置

**Comment by 836304831** [comment]
scene场景可以认为是一个图像，比如王者荣耀的大厅页面就可以看成是一个scene。
ai根据场景scene计算出来的action是一个操作，比如点击或滑动及对应的位置。可以理解为action是在当前scene下识别出来的。
动作有down，up和swipe等操作，这些操作的位置在手机上往往是固定的（可以参考王者的转盘和技能位置），action对应的就是手机上的固定位置。ai识别出来action后，只需要将action作用到指定的位置（指定的位置对应down，up和swipe等操作）
