### ISSUE TITLE
运行天天酷跑的例子出错

### ISSUE THREAD

**Issue by yuzhiyizhan** [Tencent/GameAISDK#33]
报错代码:
start service test_node failed, process GameReg.exe cfgpath D:/github/GameAISDK-master/tools/SDKTool/project/TTKP/TTKP.prj start failed, service_name: test_node error: []
控制台一直弹这些信息:
[2021-06-26 22:39:21,275][./phone_aiclientapi\WrappedDeviceAPI\deviceAPI\mobileDevice\android\plugin\Platform_plugin\PlatformWeTest\demo\TcpSocketHandler.py:173][DEBUG] : >-- heart beat <--: header {
  sequenceId: 9527
  timestamp: 1624718358771
  command: CLOUDSCREEN_HEARTBEAT_RES
}

麻烦大佬帮忙看一下
已加群麻烦通过一下QQ号码:2387301977

**Comment by nanchengjiumeng** [comment]
群号多少呀

**Comment by bujinjinyaonuli** [comment]
你好，请问你解决这个问题了吗？我也遇到同样的问题了，希望能联系QQ:643429173

**Comment by wanghaisheng** [comment]
这是个死苦 不要想了

**Comment by bujinjinyaonuli** [comment]
> 这是个死苦 不要想了

- 死苦是什么？是解决不了了吗？/(ㄒoㄒ)/~~

**Comment by wanghaisheng** [comment]
意思是没人管 没人回复的
